name: 'Code Coverage Annotations'
description: 'Annotate your pull requests to show where test coverage is missing'
author: '@ggilder'
branding:
  icon: alert-triangle
  color: orange
inputs:
  TOKEN:
    required: false
    description: 'Github token from workflow. You can use this or the APP_ID/PRIVATE_KEY combination for authentication.'
  API_BASE_URL:
    required: false
    description: 'Github base URL. Set this if you are using a GitHub Enterprise Server or a instance on `ghe.com``.'
    default: 'https://api.github.com'
  APP_ID:
    required: false
    description: 'GitHub App ID, used with PRIVATE_KEY for GitHub App authentication instead of using a TOKEN.'
  PRIVATE_KEY:
    required: false
    description: 'GitHub App private key in PEM format, used with APP_ID for GitHub App authentication instead of using a TOKEN.'
  COVERAGE_FILE_PATH:
    required: true
    description: 'Path to coverage file'
  COVERAGE_FORMAT:
    required: false
    description: 'Format of coverage file. May be `lcov`, `clover`, or `go`.'
  DEBUG:
    required: false
    description: "Log debugging information. Comma-separated list of possible values `coverage`, `pr_lines_added`"
runs:
  using: 'node16'
  main: 'dist/index.js'
